#!/bin/bash -x
XETEXCONF="--section-numbering --template=latex2e/xelatex.tex --documentclass=book --documentoptions=11pt,twoside,letterpaper --use-latex-docinfo --section-subtitles --smart-quotes=yes -l es --toc-top-backlinks --compound-enumerators"

rst2xetex ${XETEXCONF} ${1} ${2}

#sed -i '/^Generated by \\href{/d' ${2}
sed -i 's/\\begin{document}/\\title{Mejoramiento del Proceso de deshidratación mediante la construcción de un sistema de control automático}\n\\author{Daniel Rodrigo Saguez Tezanos Pinto}\n\\date{Diciembre, 2015}\n\\begin{document}/g' ${2}
sed -i 's/|,|/}{/g' ${2}
sed -i 's/{[ ]*/{/g' ${2}
sed -i 's/[ ]*}/}/g' ${2}
sed -i 's/\DUrole{imagentex}/\imagentex/g' ${2}
sed -i 's/{[ ]\+/{/g' ${2}
sed -i 's/[ ]\+}/}/g' ${2}
sed -i 's/... continued on next page/... Continua en la siguiente página/g' ${2}
sed -i 's/... continued/... continuación/g' ${2}
sed -i 's/\\setcounter{secnumdepth}{0}/\\setcounter{secnumdepth}{3}/g' ${2}
