#!/bin/bash
#
#
idioma=es
tipoDocumento=book
tamPapel=letterpaper
tamLetra=11pt
opcionesDoc=$tamPapel,$tamLetra,twoside
plantilla=latex2e/xelatex.tex

OPCIONES="--template=$plantilla --documentclass=$tipoDocumento --documentoptions=$opcionesDoc"
OPCIONES="${OPCIONES} --use-latex-docinfo --use-latex-citations --figure-citations --section-subtitles --smart-quotes=yes -r 3"
OPCIONES="${OPCIONES} --section-numbering --compound-enumerators --toc-top-backlinks -l $idioma"
rst2xetex "${OPCIONES}" "${1}" "${2}" > "${1}.log"

#sed -i '/^Generated by \\href{/d' ${2}
sed -i 's/\\begin{document}/\\title{Mejoramiento del Proceso de deshidratación mediante la construcción de un sistema de control automático}\n\\author{Daniel Rodrigo Saguez Tezanos Pinto}\n\\date{Diciembre, 2015}\n\\begin{document}/g' "${2}"
sed -i 's/|,|/}{/g' "${2}"
sed -i 's/pdf\\_tex/pdf_tex/g' "${2}"
sed -i 's/{[ ]*/{/g' "${2}"
sed -i 's/[ ]*}/}/g' "${2}"
sed -i 's/\DUrole{imagentex}/\imagentex/g' "${2}"
sed -i 's/{[ ]\+/{/g' "${2}"
sed -i 's/[ ]\+}/}/g' "${2}"
sed -i 's/... continued on next page/... Continua en la siguiente página/g' "${2}"
sed -i 's/... continued/... continuación/g' "${2}"
sed -i 's/\\setcounter{secnumdepth}{0}/\\setcounter{secnumdepth}{3}/g' "${2}"
